openapi: 3.1.0
info:
  title: Chronicle API
  version: v1alpha
servers:
  - url: 'https://{region}-chronicle.googleapis.com/{version}'
    variables:
      region:
        enum:
        - us
        - northamerica-northeast2
        - europe
        - asia-southeast1
        - europe-west2
        - australia-southeast1
        - me-west1
        - europe-west3
        - europe-west6
        - me-central2
        - asia-south1
        - asia-northeast1
        - me-central1
        - europe-west12
        default: us
      version:
        enum:
        - v1alpha
        default: v1alpha
paths:
  /projects/{project}/locations/{location}/instances/{instance}:
    get:
      description: Get a SecOps instance
      operationId: getInstance
      tags:
        - chronicle
        - getMethod
      responses:
        200:
          description: A SecOps instance name
    $ref: '#/components/pathItems/InstancePath'
  /projects/{project}/locations/{location}/instances/{instance}/logTypes:
    get:
      description: List log types
      operationId: getLogType
      tags:
        - chronicle
        - listMethod
      responses:
        200:
          description: A SecOps log type
    parameters:
      - name: pageSize
        in: query
        schema:
          type: string
    $ref: '#/components/pathItems/InstancePath'
components:
  pathItems:
    InstancePath:
      parameters:
        - name: project
          in: path
          schema:
            type: string
        - name: location
          in: path
          schema:
            type: string
        - name: instance
          in: path
          schema:
            type: string