openapi: 3.1.1
info:
  title: Chronicle API
  version: v1alpha
externalDocs:
  url: https://cloud.google.com/chronicle/docs/reference/rest
tags:
  - name: ChronicleApi
servers:
  - url: 'https://{region}-chronicle.googleapis.com/v1alpha'
    variables:
      region:
        enum:
        - us
        - northamerica-northeast2
        - europe
        - asia-southeast1
        - europe-west2
        - australia-southeast1
        - me-west1
        - europe-west3
        - europe-west6
        - me-central2
        - asia-south1
        - asia-northeast1
        - me-central1
        - europe-west12
        default: us
paths:
  /projects/{project}/locations/{location}/instances/{instance}:
    $ref: 'paths/instances.yaml#/GetInstancePath'
  /projects/{project}/locations/{location}/instances/{instance}/logTypes:
    $ref: 'paths/logTypes.yaml#/ListLogTypesPath'
  /projects/{project}/locations/{location}/instances/{instance}/logTypes/{logType}/logs:
    $ref: 'paths/logs.yaml#/ListLogsPath'